name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t cygnetops/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true cygnetops/react-test npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*' '*node_modules*' '*.dev*'

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
          aws configure set default.region us-east-2

      - name: Upload to S3 and create application version
        run: |
          aws s3 cp deploy.zip s3://elasticbeanstalk-us-east-2-770926107807/deploy-${{ github.sha }}.zip
          aws elasticbeanstalk create-application-version \
            --application-name frontend \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket=elasticbeanstalk-us-east-2-770926107807,S3Key=deploy-${{ github.sha }}.zip

      - name: Deploy to ElasticBeanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: frontend
          environment_name: Frontend-env
          existing_bucket_name: elasticbeanstalk-us-east-2-770926107807
          region: us-east-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
